DEF_BPM = 120
DEF_SCENE_LENGTH = 16*24   #Beats to ticks

DEF_SHAPE = "Circle"

DEF_CLIP_LENGTH = 4    #Bars
DEF_CLIP_START = 0


DEF_MOVEMENT_CLIP_TYPE = "None"

DEF_STATIC_LOCATION = (200, 200)
DEF_START_LOCATION = (0, 0)

DEF_END_LOCATION = (1, 1)

DEF_C_CENTER_LOCATION = (.5, .5)
DEF_C_START_DEGREES = 0
DEF_C_END_DEGREES = 360
DEF_C_RADIUS = .25

DEF_S_CENTER_LOCATION = (.5, .5)
DEF_S_START_DEGREES = 0
DEF_S_END_DEGREES = 360
DEF_S_START_RADIUS = 0
DEF_S_END_RADIUS = .5


DEF_COLOR_CLIP_TYPE = 'None'

DEF_STATIC_COLOR = (256,256,256)

DEF_COLOR_1_TIME = 1    #BEATS
DEF_COLOR_2_TIME = 1    #BEATS
DEF_COLOR_1 = (256,256,256)
DEF_COLOR_2 = (0,0,0)

DEF_FROM_COLOR = (0,0,0)
DEF_TO_COLOR = (256,256,256)



#Event types for things that aren't a part of TK
MODELUPDATE = 0
VIEWUPDATE = 1

PAUSE_STATE = 0
PLAY_STATE = 1