RESOLUTION = (500,300)
RES_RATIO = RESOLUTION[0]/RESOLUTION[1]

SCREEN_WIDTH, SCREEN_HEIGHT = RESOLUTION

MIDDLE_POINT = (SCREEN_WIDTH/2 ,SCREEN_HEIGHT/2)


DEF_LIGHT_SIZE = 20
DEF_BPM = 120
DEF_SCENE_LENGTH = 16*24   #Beats to ticks

DEF_SHAPE = "Circle"

DEF_CLIP_LENGTH = 16    #Bars
DEF_CLIP_START = 0


DEF_MOVEMENT_CLIP_TYPE = "None"

DEF_STATIC_LOCATION = MIDDLE_POINT
DEF_START_LOCATION = (0, 0)

DEF_END_LOCATION = RESOLUTION

DEF_C_CENTER_LOCATION = MIDDLE_POINT
DEF_C_START_DEGREES = 0
DEF_C_END_DEGREES = 4
DEF_C_RADIUS = 50

DEF_S_CENTER_LOCATION = MIDDLE_POINT
DEF_S_START_DEGREES = 0
DEF_S_END_DEGREES = 4
DEF_S_START_RADIUS = 0
DEF_S_END_RADIUS = 50


DEF_COLOR_CLIP_TYPE = 'None'

DEF_STATIC_COLOR = (256,256,256)

DEF_COLOR_1_TIME = 1    #BEATS
DEF_COLOR_2_TIME = 1    #BEATS
DEF_COLOR_1 = (256,256,256)
DEF_COLOR_2 = (0,0,0)

DEF_FROM_COLOR = (0,0,0)
DEF_TO_COLOR = (256,256,256)





#Event types for things that aren't a part of TK
MODELUPDATE = 0
VIEWUPDATE = 1

PAUSE_STATE = 0
PLAY_STATE = 1

LIVE_PLAY = 0
LIVE_EDIT = 1
LIVE_LOAD = 2

FILE_EXTENSION = ".txt"


DEF_SELECTION_PANEL_DIMENSIONS = (4,4)